To install a Python library in Google Colab, you can use the `pip install` command. The `!` at the beginning tells Colab to run the command as a shell command.

In [1]:
# Install a library, for example 'numpy'
!pip install numpy

# You can then import and use the library
import numpy as np
print(np.__version__)

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
2.0.2

In [2]:
from google.colab import files
uploaded = files.upload()

Saving daily-rainfall-at-state-level.csv to daily-rainfall-at-state-level.csv

In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv("daily-rainfall-at-state-level.csv")

In [4]:
df

,id,date,state_code,state_name,actual,rfs,normal,deviation
0,0,2009-01-01,5,Uttarakhand,0.0,0.003906,2.19,-100.0
1,1,2009-01-01,18,Assam,0.0,0.000000,0.52,-100.0
2,2,2009-01-01,16,Tripura,0.0,0.000000,0.09,-100.0
3,3,2009-01-01,36,Telangana,0.0,0.000000,0.17,-100.0
4,4,2009-01-01,2,Himachal Pradesh,0.0,0.008566,3.31,-100.0
...,...,...,...,...,...,...,...,...
204871,204871,2024-07-27,38,The Dadra And Nagar Haveli And Daman And Diu,NaN,0.000000,7.40,NaN
204872,204872,2024-07-28,38,The Dadra And Nagar Haveli And Daman And Diu,NaN,0.000000,8.30,NaN
204873,204873,2024-07-29,38,The Dadra And Nagar Haveli And Daman And Diu,NaN,0.000000,5.40,NaN
204874,204874,2024-07-30,38,The Dadra And Nagar Haveli And Daman And Diu,NaN,0.000000,7.30,NaN
204875,204875,2024-07-31,38,The Dadra And Nagar Haveli And Daman And Diu,NaN,0.000000,4.20,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204876 entries, 0 to 204875
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          204876 non-null  int64
 1   date        204876 non-null  object
 2   state_code  204876 non-null  int64
 3   state_name  204876 non-null  object
 4   actual      187714 non-null  float64
 5   rfs         199011 non-null  float64
 6   normal      193358 non-null  float64
 7   deviation   173855 non-null  float64
dtypes: float64(4), int64(2), object(2)
memory usage: 12.5+ MB

In [6]:
df.head()

,id,date,state_code,state_name,actual,rfs,normal,deviation
0,0,2009-01-01,5,Uttarakhand,0.0,0.003906,2.19,-100.0
1,1,2009-01-01,18,Assam,0.0,0.000000,0.52,-100.0
2,2,2009-01-01,16,Tripura,0.0,0.000000,0.09,-100.0
3,3,2009-01-01,36,Telangana,0.0,0.000000,0.17,-100.0
4,4,2009-01-01,2,Himachal Pradesh,0.0,0.008566,3.31,-100.0

In [7]:
df.isnull()

           id   date  state_code  state_name  actual    rfs  normal  deviation
0       False  False       False       False   False  False   False      False
1       False  False       False       False   False  False   False      False
2       False  False       False       False   False  False   False      False
3       False  False       False       False   False  False   False      False
4       False  False       False       False   False  False   False      False
...       ...    ...         ...         ...     ...    ...     ...        ...
204871  False  False       False       False    True  False   False       True
204872  False  False       False       False    True  False   False       True
204873  False  False       False       False    True  False   False       True
204874  False  False       False       False    True  False   False       True
204875  False  False       False       False    True  False   False       True

[204876 rows x 8 columns]

In [9]:
df.isnull().sum()

id                0
date              0
state_code        0
state_name        0
actual        17162
rfs            5865
normal        11518
deviation     31021
dtype: int64

In [10]:
print(df["actual"])

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
204871    NaN
204872    NaN
204873    NaN
204874    NaN
204875    NaN
Name: actual, Length: 204876, dtype: float64

In [13]:
df['date'] = pd.to_datetime(df['date'])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204876 entries, 0 to 204875
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          204876 non-null  int64
 1   date        204876 non-null  datetime64[ns]
 2   state_code  204876 non-null  int64
 3   state_name  204876 non-null  object
 4   actual      187714 non-null  float64
 5   rfs         199011 non-null  float64
 6   normal      193358 non-null  float64
 7   deviation   173855 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 12.5+ MB

In [17]:
df.columns

Index(['id', 'date', 'state_code', 'state_name', 'actual', 'rfs', 'normal',
       'deviation'],
      dtype='object')

In [18]:
df.describe()

,id,date,state_code,actual,rfs,normal,deviation
count,204876.000000,204876,204876.000000,187714.000000,199011.000000,193358.000000,173855.000000
mean,102437.500000,2016-10-16 00:00:00.000000256,19.166667,3.990693,9.643683,4.654058,38.516222
min,0.000000,2009-01-01 00:00:00,1.000000,0.000000,0.000000,0.000000,-100.000000
25%,51218.750000,2012-11-23 00:00:00,9.750000,0.000000,0.000000,0.420000,-100.000000
50%,102437.500000,2016-10-16 00:00:00,18.500000,0.150000,0.063856,1.870000,-89.060000
75%,153656.250000,2020-09-08 00:00:00,29.250000,3.890000,5.685068,6.760000,-9.045000
max,204875.000000,2024-07-31 00:00:00,38.000000,283.000000,658.765073,97.680000,362300.000000
std,59142.751213,NaN,11.171668,9.512507,27.504865,7.369770,1367.744520

In [20]:
df.shape

(204876, 8)

In [21]:
df.to_csv('cleaned_rainfall.csv', index=False)
from google.colab import files
files.download('cleaned_rainfall.csv')

In [22]:
print(df.isnull().sum())

id                0
date              0
state_code        0
state_name        0
actual        17162
rfs            5865
normal        11518
deviation     31021
dtype: int64

In [ ]:
df['actual'].fillna(df['actual'].mean(), inplace =True)

In [ ]:
df['rfs'].fillna(df['rfs'].mean(), inplace =True)

In [ ]:
df['normal'].fillna(df['normal'].mean(), inplace =True)

In [27]:
print(df['deviation'])

0        -100.0
1        -100.0
2        -100.0
3        -100.0
4        -100.0
          ...
204871      NaN
204872      NaN
204873      NaN
204874      NaN
204875      NaN
Name: deviation, Length: 204876, dtype: float64

In [ ]:
df['deviation'].fillna(df['deviation'].mean(), inplace =True)

In [29]:
df.isnull().sum()

id            0
date          0
state_code    0
state_name    0
actual        0
rfs           0
normal        0
deviation     0
dtype: int64

In [30]:
#checking negative value

In [32]:
df[df['actual'] < 0]

Empty DataFrame
Columns: [id, date, state_code, state_name, actual, rfs, normal, deviation]
Index: []

In [33]:
#Forecast rainfall
df[df['rfs'] < 0]

Empty DataFrame
Columns: [id, date, state_code, state_name, actual, rfs, normal, deviation]
Index: []

In [34]:
df = df[
    (df['actual'] >= 0) &
    (df['rfs'] >= 0) &
    (df['normal'] >= 0)
]

In [35]:
df.describe()

,id,date,state_code,actual,rfs,normal,deviation
count,204876.000000,204876,204876.000000,204876.000000,204876.000000,204876.000000,204876.000000
mean,102437.500000,2016-10-16 00:00:00.000000256,19.166667,3.990693,9.643683,4.654058,38.516222
min,0.000000,2009-01-01 00:00:00,1.000000,0.000000,0.000000,0.000000,-100.000000
25%,51218.750000,2012-11-23 00:00:00,9.750000,0.000000,0.000000,0.460000,-100.000000
50%,102437.500000,2016-10-16 00:00:00,18.500000,0.380000,0.105405,2.250000,-69.960000
75%,153656.250000,2020-09-08 00:00:00,29.250000,3.990693,7.157895,6.370000,38.516222
max,204875.000000,2024-07-31 00:00:00,38.000000,283.000000,658.765073,97.680000,362300.000000
std,59142.751213,NaN,11.171668,9.105371,27.108312,7.159610,1259.948645

In [36]:
df.to_csv('cleaned_rainfall.csv', index=False)
from google.colab import files
files.download('cleaned_rainfall.csv')